apiVersion: v1
kind: Service
metadata:
  name: event-app-service
  namespace: event-booking
spec:
  selector:
    app: event-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
