apiVersion: v1
kind: Service
metadata:
  name: event-db
  namespace: event-booking
spec:
  selector:
    app: event-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
