name: CI/CD

on:
  push:
    branches: [ master ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3
      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # Build the app with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./lab
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Build Docker image
      - name: Build Docker Image
        run: docker build -t mmcc123/lab:latest ./lab
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Push Docker image
      - name: Push Docker Image
        run: docker push mmcc123/lab:latest
      # (Optional) Set up kubectl 
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'
